/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.5
 * Generated at: 2023-05-08 07:42:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class createform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Create Event</title>\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"createform.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <img src=\"logo.png\"  width = \"150px\" height=\"80px\" top=\"20px\" left=\"0px\" class=\"logo\">\r\n");
      out.write("    <div class=\"background-image\"></div>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("  \r\n");
      out.write("    <h2>CREATE EVENT</h2>\r\n");
      out.write("    <form action=\"createvent\" method=\"post\">\r\n");
      out.write("      <label for=\"event-name\">EVENT NAME:</label>\r\n");
      out.write("      <input type=\"text\" id=\"event-name\" name=\"event-name\" required>\r\n");
      out.write("\r\n");
      out.write("      <label for=\"event-date\">EVENT DATE:</label>\r\n");
      out.write("      <input type=\"date\" id=\"event-date\" name=\"event-date\" style=\"width: 97%;\" required>\r\n");
      out.write("\r\n");
      out.write("      <label for=\"event-location\">EVENT LOCATION:</label>\r\n");
      out.write("      <input type=\"text\" id=\"event-location\" name=\"event-location\" required>\r\n");
      out.write("\r\n");
      out.write("      <label for=\"event-type\">TYPE OF EVENT:</label>\r\n");
      out.write("      <select id=\"event-type\" name=\"event-type\" required>\r\n");
      out.write("        <option value=\"culture\">Cultural</option>\r\n");
      out.write("        <option value=\"sport\">Sports</option>\r\n");
      out.write("        <option value=\"art\">Arts</option>\r\n");
      out.write("        <option value=\"social\">Social</option>\r\n");
      out.write("        <option value=\"technical\">Technical</option>\r\n");
      out.write("        <option value=\"other\">Other</option>\r\n");
      out.write("      </select>\r\n");
      out.write("\r\n");
      out.write("      <label for=\"organizing-club\">ORGANIZING CLUB:</label>\r\n");
      out.write("      <select id=\"organizing-club\" name=\"organizing-club\" required>\r\n");
      out.write("        <option value=\"club1\">Select Club Name</option>\r\n");
      out.write("        <option value=\"NIET Cricket Club\">NIET Cricket Club</option>\r\n");
      out.write("        <option value=\"NIET FootBall Club\">NIET FootBall Club</option>\r\n");
      out.write("        <option value=\"NIET VolleyBallL Club\">NIET VolleyBallL Club</option>\r\n");
      out.write("        <option value=\"NIET BasketBall Club\">NIET BasketBall Club</option>\r\n");
      out.write("        <option value=\"NIET Indoor Games (Boys, Girls)\">NIET Indoor Games (Boys, Girls) </option>\r\n");
      out.write("        <option value=\"NIET Kabbadi Club\">NIET Kabbadi Club </option>\r\n");
      out.write("        <option value=\"NIET Yoga Club\">NIET Yoga Club </option>\r\n");
      out.write("        <option value=\"NIET  Athletics Club\">NIET  Athletics Club </option>\r\n");
      out.write("        <option value=\"Dance Club\">Dance Club</option>\r\n");
      out.write("        <option value=\"Music Club\">Music Club</option>\r\n");
      out.write("        <option value=\"Theatre Club\">Theatre Club </option>\r\n");
      out.write("        <option value=\"Editorial Club\">Editorial Club</option>\r\n");
      out.write("        <option value=\"Kalakriti -Fine Arts and Paint Club\">Kalakriti -Fine Arts and Paint Club</option>\r\n");
      out.write("        <option value=\"Megapixels-Photography Club\">Megapixels-Photography Club</option>\r\n");
      out.write("        <option value=\"Jetsetters: Youth Tourism Club\">Jetsetters: Youth Tourism Club</option>\r\n");
      out.write("        <option value=\"Khushiya Baato Club\">Khushiya Baato Club </option>\r\n");
      out.write("        <option value=\"Green Gold Club\">Green Gold Club</option>\r\n");
      out.write("        <option value=\"CodeTronics\">CodeTronics</option>\r\n");
      out.write("        <option value=\"IETE Students Forum\">IETE Students Forum</option>\r\n");
      out.write("        <option value=\"REBOOT: Code eN-Coders\">REBOOT: Code eN-Coders</option>\r\n");
      out.write("        <option value=\"Technocrafts Club\">Technocrafts Club</option>\r\n");
      out.write("        <option value=\"ISTE (Indian Society of Technical Education)\">ISTE (Indian Society of Technical Education)</option>\r\n");
      out.write("        <option value=\"CSI\">CSI</option>\r\n");
      out.write("        <option value=\"NIET Coding Club\">NIET Coding Club</option>\r\n");
      out.write("        <option value=\"ProNetiX\">ProNetiX</option>\r\n");
      out.write("        <option value=\"Google Developers Students Club\">Google Developers Students Club </option>\r\n");
      out.write("        <option value=\"CodeChef NIET Chapter\">CodeChef NIET Chapter</option>\r\n");
      out.write("        <option value=\"The Mindbenders\">The Mindbenders</option>\r\n");
      out.write("        <option value=\"EmergeX\">EmergeX </option>\r\n");
      out.write("        <option value=\"DODGE Gaming\">DODGE Gaming</option>\r\n");
      out.write("        <option value=\"DLT Club\">DLT Club</option>\r\n");
      out.write("        <option value=\"AWS Club\">AWS Club</option>\r\n");
      out.write("        <option value=\"CYBERHACK Club\">CYBERHACK Club</option>\r\n");
      out.write("        <option value=\"Design Thinkers Club\">Design Thinkers Club</option>\r\n");
      out.write("        <option value=\"Signodes\">Signodes</option>\r\n");
      out.write("        <option value=\"DNA society of Biotechnology\">DNA society of Biotechnology</option>\r\n");
      out.write("        <option value=\"Electrifier\">Electrifier</option>\r\n");
      out.write("        <option value=\"CHESS (Chemical Engineering Student Society)\">CHESS (Chemical Engineering Student Society)</option>\r\n");
      out.write("      </select>\r\n");
      out.write("\r\n");
      out.write("      <label for=\"file-upload\">POSTER UPLOAD:</label>\r\n");
      out.write("      <input type=\"file\" id=\"file-upload\" name=\"file-upload\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <input type=\"submit\" value=\"Create Event\">\r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
