/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.5
 * Generated at: 2023-05-08 04:59:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class cultural_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Cultural Clubs</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"cultural.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"hero\">\r\n");
      out.write("        <img src=\"logo.png\" alt=\"\" class=\"logo\">\r\n");
      out.write("        <p class=\"club\">CULTURAL CLUBS</p>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"clubs.jsp\">Clubs</a></li>\r\n");
      out.write("                <li><a href=\"cover.jsp\">Login</a></li>\r\n");
      out.write("                <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"extra\">\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("            <div class=\"card\" id=\"myBtn\"><img src=\"dance.png\">\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h2>DANCE CLUB</h2>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"myModal\" class=\"modal\">\r\n");
      out.write("                <!-- Modal content -->\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                  <span class=\"close\">&times;</span>\r\n");
      out.write("                  <img src=\"dance.png\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                  <div class=\"content\">\r\n");
      out.write("                    <h1 class=\"club-name\">Juventas Club</h1>\r\n");
      out.write("                  <p class=\"para\">\r\n");
      out.write("                    Juventas is the oldest dance club of NIET. \r\n");
      out.write("This club encourage the students to showcase their talent in dance under any dance form with fun.</p>\r\n");
      out.write("                    <p class=\"president\">\r\n");
      out.write("                      President: \r\n");
      out.write("                      <p class=\"president_name\">\r\n");
      out.write("                        Shweta Srivastava\r\n");
      out.write("                      </p>\r\n");
      out.write("                      <p class=\"contact-president\">\r\n");
      out.write("                        Contact:- +91 7827482395\r\n");
      out.write("                      </p>\r\n");
      out.write("                      \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"Faculty\">\r\n");
      out.write("                      Faculty Incharge: \r\n");
      out.write("                      <p class=\"faculty_name\">\r\n");
      out.write("                        Ms Kanika Taneja, AP,  ECE Deptt\r\n");
      out.write("                      </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("<!-- MUSIC-CARD-------------------- -->\r\n");
      out.write("            <div class=\"card\" id=\"myBtn2\"><img src=\"music.png\"/>\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h1>MUSIC CLUB</h1>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"myModal2\" class=\"modal2\">\r\n");
      out.write("              <!-- Modal content -->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close2\">&times;</span>\r\n");
      out.write("                <img src=\"music.png\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                  <h1 class=\"club-name\">Music Club</h1>\r\n");
      out.write("                <p class=\"para\">\r\n");
      out.write("                  The music club is specializes in hosting live music performances by various artists and bands. our club are often intimate and provide a unique atmosphere for music lovers to enjoy live performances of various genres such as jazz, rock, blues, country, and many others. Additionally, music club may also offer food and drinks, creating a complete experience for music enthusiasts.</p>\r\n");
      out.write("                  <p class=\"president\">\r\n");
      out.write("                    President: \r\n");
      out.write("                    <p class=\"president_name\">\r\n");
      out.write("                      Sahil Sharma\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"contact-president\">\r\n");
      out.write("                      Contact:- +91 9728681020\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"Faculty\">\r\n");
      out.write("                    Faculty Incharge: \r\n");
      out.write("                    <p class=\"faculty_name\">\r\n");
      out.write("                     Mr Himanshu Yadav, AP, ECE Deptt\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("<!-- THEATRE CLUB------------------ -->\r\n");
      out.write("            <div class=\"card\" id=\"myBtn3\"><img src=\"theatre.png\"/>\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h1>THEATRE CLUB</h1>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"myModal3\" class=\"modal3\">\r\n");
      out.write("              <!-- Modal content -->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close3\">&times;</span>\r\n");
      out.write("                <img src=\"theatre.png\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                  <h1 class=\"club-name\">Theatre Club</h1>\r\n");
      out.write("                <p class=\"para\">\r\n");
      out.write("                  The  theatre club  focuses on producing and showcasing theatrical productions. our club composed of actors, directors, playwrights, producers, and other individuals with a passion for theatre. we typically organize and rehearse plays, musicals, and other dramatic performances and present them to an audience in a dedicated theatre venue.</p>\r\n");
      out.write("                  <p class=\"president\">\r\n");
      out.write("                    President: \r\n");
      out.write("                    <p class=\"president_name\">\r\n");
      out.write("                      Astha Gupta \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"contact-president\">\r\n");
      out.write("                      Contact:- +91 7017036949\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"Faculty\">\r\n");
      out.write("                    Faculty Incharge: \r\n");
      out.write("                    <p class=\"faculty_name\">\r\n");
      out.write("                      Dr. Amba , AP IT Deptt\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("            <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("          \r\n");
      out.write("    </div>\r\n");
      out.write(" \r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"cultural.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
