/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.5
 * Generated at: 2023-05-08 04:59:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class technical_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Technical Clubs</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"technical.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"hero\">\r\n");
      out.write("        <img src=\"logo.png\" alt=\"\" class=\"logo\">\r\n");
      out.write("        <p class=\"club\">TECHNICAL CLUBS</p>\r\n");
      out.write("        <nav>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li><a href=\"index.jsp\">Home</a></li>\r\n");
      out.write("                <li><a href=\"clubs.jsp\">Clubs</a></li>\r\n");
      out.write("                <li><a href=\"cover.jsp\">Login</a></li>\r\n");
      out.write("                <li><a href=\"#\">About Us</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </nav>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"extra\">\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("            <div class=\"card\" id=\"myBtn\"><img src=\"reboot.jpg\">\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h2>REBOOT CLUB</h2>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"myModal\" class=\"modal\">\r\n");
      out.write("                <!-- Modal content -->\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                  <span class=\"close\">&times;</span>\r\n");
      out.write("                  <img src=\"reboot.jpg\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                  <div class=\"content\">\r\n");
      out.write("                    <h1 class=\"club-name\">Reboot Club</h1>\r\n");
      out.write("                  <p class=\"para\">\r\n");
      out.write("                    The Reboot Club is a college club of the Computer Science and Engineering (CSE) department. Our club is dedicated to exploring the latest trends and innovations in the tech industry by organizing various tech-related events, such as tech quizzes and competitions.</p>\r\n");
      out.write("                    <p class=\"president\">\r\n");
      out.write("                      President: \r\n");
      out.write("                      <p class=\"president_name\">\r\n");
      out.write("                        Nikhil\r\n");
      out.write("                      </p>\r\n");
      out.write("                      <p class=\"contact-president\">\r\n");
      out.write("                        Contact:- +91 7991761688\r\n");
      out.write("                      </p>\r\n");
      out.write("                      \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"Faculty\">\r\n");
      out.write("                      Faculty Incharge: \r\n");
      out.write("                      <p class=\"faculty_name\">\r\n");
      out.write("                        Dr. Kumud Saxena, HoD, CSE IT\r\n");
      out.write("                      </p>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("<!-- PRONETIX-CARD-------------------- -->\r\n");
      out.write("            <div class=\"card\" id=\"myBtn2\"><img src=\"protinex.png\"/>\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h1>PRONETIX</h1>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"myModal2\" class=\"modal2\">\r\n");
      out.write("              <!-- Modal content -->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close2\">&times;</span>\r\n");
      out.write("                <img src=\"protinex.jpg\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                  <h1 class=\"club-name\">Pronetix Club</h1>\r\n");
      out.write("                <p class=\"para\">\r\n");
      out.write("                  The Indian Society for Technical Education (ISTE) is the leading National Professional non-profit making Society for the Technical Education System in our country with the motto of Career Development of Teachers and Personality Development of Students and overall development of our Technical Education System.</p>\r\n");
      out.write("                  <p class=\"president\">\r\n");
      out.write("                    President: \r\n");
      out.write("                    <p class=\"president_name\">\r\n");
      out.write("                      Nikhil\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"contact-president\">\r\n");
      out.write("                      Contact:- +91 7991761688\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"Faculty\">\r\n");
      out.write("                    Faculty Incharge: \r\n");
      out.write("                    <p class=\"faculty_name\">\r\n");
      out.write("                      Ms. Aditee Mattoo, AP &Dy. Head, CSE M.Tech Int.\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("<!-- ISTE CLUB------------------ -->\r\n");
      out.write("            <div class=\"card\" id=\"myBtn3\"><img src=\"ISTE.png\"/>\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h1>ISTE</h1>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"myModal3\" class=\"modal3\">\r\n");
      out.write("              <!-- Modal content -->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close3\">&times;</span>\r\n");
      out.write("                <img src=\"ISTE.png\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                  <h1 class=\"club-name\">ISTE Club</h1>\r\n");
      out.write("                <p class=\"para\">\r\n");
      out.write("                  The Indian Society for Technical Education (ISTE) is the leading National Professional non-profit making Society for the Technical Education System in our country with the motto of Career Development of Teachers and Personality Development of Students and overall development of our Technical Education System.</p>\r\n");
      out.write("                  <p class=\"president\">\r\n");
      out.write("                    President: \r\n");
      out.write("                    <p class=\"president_name\">\r\n");
      out.write("                      Astha Gupta \r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"contact-president\">\r\n");
      out.write("                      Contact:- +91 7017036949\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"Faculty\">\r\n");
      out.write("                    Faculty Incharge: \r\n");
      out.write("                    <p class=\"faculty_name\">\r\n");
      out.write("                      Dr. Amba , AP IT Deptt\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("          \r\n");
      out.write("            <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("          \r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("            <div class=\"card\" id=\"myBtn4\" ><img src=\"CSI.png\">\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h1>CSI</h1>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"myModal4\" class=\"modal4\">\r\n");
      out.write("              <!-- Modal content -->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close4\">&times;</span>\r\n");
      out.write("                <img src=\"CSI.png\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                  <h1 class=\"club-name\">CSI Club</h1>\r\n");
      out.write("                <p class=\"para\">\r\n");
      out.write("                  CSI or Computer Society of India is a new student chapter introduced recently. The Computer Society of India is a non-profit professional meet to exchange views and information to learn and share ideas. The wide spectrum of members is committed to the advancement of theory and practice of Computer Engineering and Technology Systems, Science and Engineering and related Arts and Sciences.\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("                  <p class=\"president\">\r\n");
      out.write("                    President: \r\n");
      out.write("                    <p class=\"president_name\">\r\n");
      out.write("                      Abhishek Yadav\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"contact-president\">\r\n");
      out.write("                      Contact:- +91 7843909018\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"Faculty\">\r\n");
      out.write("                    Faculty Incharge: \r\n");
      out.write("                    <p class=\"faculty_name\">\r\n");
      out.write("                      Mr. Abdul Khalid, AP IT\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("            <div class=\"card\" id=\"myBtn5\"><img src=\"NIET CODING CLUB.png\"/>\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h1>NIET CODING CLUB</h1>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div id=\"myModal5\" class=\"modal5\">\r\n");
      out.write("              <!-- Modal content -->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close5\">&times;</span>\r\n");
      out.write("                <img src=\"NIET CODING CLUB.png\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                  <h1 class=\"club-name\">NIET Coding Club</h1>\r\n");
      out.write("                <p class=\"para\">\r\n");
      out.write("                  Niet Coding Club provides participating students an opportunity to learn the basics of computer programming in a team . The club's main focus is on creating applications, websites, games, stem/steam workshops, and other projects.\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("                  <p class=\"president\">\r\n");
      out.write("                    President: \r\n");
      out.write("                    <p class=\"president_name\">\r\n");
      out.write("                      Riya Bisht\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"contact-president\">\r\n");
      out.write("                      Contact:- +91 8076475243\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"Faculty\">\r\n");
      out.write("                    Faculty Incharge: \r\n");
      out.write("                    <p class=\"faculty_name\">\r\n");
      out.write("                      Mr. Ankur Chaudhary, AP IT Deptt. \r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\" id=\"myBtn6\"><img src=\"gdsc.png\"/>\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h1>GOOGLE DEVELOPER STUDENT CLUB</h1>\r\n");
      out.write("                <p></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"myModal6\" class=\"modal6\">\r\n");
      out.write("              <!-- Modal content -->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close6\">&times;</span>\r\n");
      out.write("                <img src=\"gdsc.png\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                  <h1 class=\"club-name\">Google Developers Student Club </h1>\r\n");
      out.write("                <p class=\"para\">\r\n");
      out.write("                  Google Developer Student Clubs are university-based community groups for students interested in Google developer technologies. It is a platform for students to build, create and innovate as they solve problems around them with the help of technology.\r\n");
      out.write("                  The community prides itself on being an inclusive environment where students from all undergraduate or graduate programs with an interest in growing as a developer are welcome to join.\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("                  <p class=\"president\">\r\n");
      out.write("                    President: \r\n");
      out.write("                    <p class=\"president_name\">\r\n");
      out.write("                      Akash Srivastava\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"contact-president\">\r\n");
      out.write("                      Contact:- +91 8076475243\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"Faculty\">\r\n");
      out.write("                    Faculty Incharge: \r\n");
      out.write("                    <p class=\"faculty_name\">\r\n");
      out.write("                      Dr Kumud Saxena, Prof, CSE/IT/MTech \r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <div class=\"wrapper\">\r\n");
      out.write("            <div class=\"card\" id=\"myBtn7\" ><img src=\"Dodge.png\">\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h1>DODGE GAMING</h1>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"myModal7\" class=\"modal7\">\r\n");
      out.write("              <!-- Modal content -->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close7\">&times;</span>\r\n");
      out.write("                <img src=\"Dodge.png\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                  <h1 class=\"club-name\">Dodge Gaming Club </h1>\r\n");
      out.write("                <p class=\"para\">\r\n");
      out.write("                  Dodge Gaming Club is an Online Club for Gaming enthusiast's of our college.\r\n");
      out.write("                  Our club handle and manage all online competative gaming like Valorant,Fifa , BGMI etc Gaming events.\r\n");
      out.write("                  These events are Intra College as well as intercollege to\r\n");
      out.write("                  Our club  has organised 7 major events in the timespan of 10 months\r\n");
      out.write("                  In which 3 were intercollege tournaments\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("                  <p class=\"president\">\r\n");
      out.write("                    President: \r\n");
      out.write("                    <p class=\"president_name\">\r\n");
      out.write("                      Shubham Chaudhary\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"contact-president\">\r\n");
      out.write("                      Contact:- +91 7905879672\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"Faculty\">\r\n");
      out.write("                    Faculty Incharge: \r\n");
      out.write("                    <p class=\"faculty_name\">\r\n");
      out.write("                      Mr. Anubhav Kumar, AP, IT \r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\" id=\"myBtn8\"><img src=\"CYBER.png\"/>\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h1>CYBERHACK</h1>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"myModal8\" class=\"modal8\">\r\n");
      out.write("              <!-- Modal content -->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close8\">&times;</span>\r\n");
      out.write("                <img src=\"CYBER.png\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                  <h1 class=\"club-name\">Cyberhack Club </h1>\r\n");
      out.write("                <p class=\"para\">\r\n");
      out.write("                  \r\n");
      out.write("                  Cyberhack club is related to cyber security and ethical hacking in which we try to make students aware of cyber attacks, like how their data is compromised. Different aspects of attacks how it is done and deeper knowledge of cyber security. And we try to teach how hacking is done, how you could be safe. \r\n");
      out.write("                  We make students know what actually hacking is, hacking is not how it looks like, what's the reality behind it.\r\n");
      out.write("\r\n");
      out.write("</p>\r\n");
      out.write("                  <p class=\"president\">\r\n");
      out.write("                    President: \r\n");
      out.write("                    <p class=\"president_name\">\r\n");
      out.write("                      Udit Gautam\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"contact-president\">\r\n");
      out.write("                      Contact:- +91 8318627909\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"Faculty\">\r\n");
      out.write("                    Faculty Incharge: \r\n");
      out.write("                    <p class=\"faculty_name\">\r\n");
      out.write("                      Mr. Sover Singh, AP, CSDS \r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card\" id=\"myBtn9\"><img src=\"emergex.png\"/>\r\n");
      out.write("              <div class=\"info\">\r\n");
      out.write("                <h1>EMERGEX</h1>\r\n");
      out.write("                <p></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"myModal9\" class=\"modal9\">\r\n");
      out.write("              <!-- Modal content -->\r\n");
      out.write("              <div class=\"modal-content\">\r\n");
      out.write("                <span class=\"close9\">&times;</span>\r\n");
      out.write("                <img src=\"emergex.png\" alt=\"\" class=\"popcard\">\r\n");
      out.write("                <div class=\"content\">\r\n");
      out.write("                  <h1 class=\"club-name\">Emergex Club </h1>\r\n");
      out.write("                <p class=\"para\">\r\n");
      out.write("                  As the name of the club itself tells us this Club seeks to create awareness towards emerging technologies and organised a number of events related to the emerging technologies like AI Meet, Data Science Day, Emerging week and many more.\r\n");
      out.write("This club was made with the aim to make all the students know the importance of thier branches and what can they achieve with that subject. This club is seeing it's future to create more such events in the near future.\r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"president\">\r\n");
      out.write("                    President: \r\n");
      out.write("                    <p class=\"president_name\">\r\n");
      out.write("                      Rakshit Sangal\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"contact-president\">\r\n");
      out.write("                      Contact:- +91 9045068087\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                  <p class=\"Faculty\">\r\n");
      out.write("                    Faculty Incharge: \r\n");
      out.write("                    <p class=\"faculty_name\">\r\n");
      out.write("                      Dr. Priyanka Chandani\r\n");
      out.write("                    </p>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("              </div>\r\n");
      out.write("              <!-- <button value=\"submit\">GALLERY</button> -->\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script src=\"technical.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
